/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all projects
         * @description Returns a list of all projects in the portfolio
         */
        get: operations["get_projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single project by ID
         * @description Returns a single project if found, or 404 if not found
         */
        get: operations["get_project_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Represents the proficiency level in a technology
         * @enum {string}
         */
        Proficiency: "Beginner" | "Intermediate" | "Advanced" | "Expert";
        /** @description Represents a portfolio project with its details and metadata */
        Project: {
            /** @description Detailed description of the project */
            description: string;
            /** @description Optional GitHub repository URL for the project */
            github_url?: string | null;
            /**
             * Format: int32
             * @description Unique identifier for the project
             */
            id: number;
            /**
             * Format: int32
             * @description Optional job ID associated with the project
             */
            job_id?: number | null;
            /** @description Title of the project */
            name: string;
            /** @description List of technologies used in the project */
            skills: components["schemas"]["Skill"][];
        };
        /** @description Represents a technology/tool used in projects */
        Skill: {
            /** @description Description of the technology */
            description: string;
            /**
             * Format: int32
             * @description Unique identifier for the technology
             */
            id: number;
            /** @description Name of the technology */
            name: string;
            /** @description Official website URL for the technology */
            official_site_url: string;
            /** @description Proficiency level in the technology */
            proficiency: components["schemas"]["Proficiency"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_project_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the project to retrieve */
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
