name: Deploy to Google Cloud Storage

on:
  push:
    branches: [ main ]

env:
  FRONTEND_BUCKET: sindbad-portfolio-frontend-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure CORS
        run: |
          gsutil cors set cors.json gs://$FRONTEND_BUCKET

      - name: Upload files
        run: |
          # Clear existing files
          gsutil -m rm -r gs://$FRONTEND_BUCKET/** || true
          
          # Upload all files
          gsutil -m cp -r out/* gs://$FRONTEND_BUCKET/
          
          # Set content types and cache control
          gsutil -m setmeta -h "Content-Type:text/html" -h "Cache-Control:public, max-age=3600" gs://$FRONTEND_BUCKET/*.html
          gsutil -m setmeta -h "Content-Type:text/css" -h "Cache-Control:public, max-age=3600" gs://$FRONTEND_BUCKET/**/*.css
          gsutil -m setmeta -h "Content-Type:application/javascript" -h "Cache-Control:public, max-age=3600" gs://$FRONTEND_BUCKET/**/*.js
          gsutil -m setmeta -h "Content-Type:image/png" -h "Cache-Control:public, max-age=3600" gs://$FRONTEND_BUCKET/**/*.png
          gsutil -m setmeta -h "Content-Type:image/jpeg" -h "Cache-Control:public, max-age=3600" gs://$FRONTEND_BUCKET/**/*.jpg
          gsutil -m setmeta -h "Content-Type:image/svg+xml" -h "Cache-Control:public, max-age=3600" gs://$FRONTEND_BUCKET/**/*.svg
          gsutil -m setmeta -h "Content-Type:application/font-woff" -h "Cache-Control:public, max-age=3600" gs://$FRONTEND_BUCKET/**/*.woff
          gsutil -m setmeta -h "Content-Type:application/font-woff2" -h "Cache-Control:public, max-age=3600" gs://$FRONTEND_BUCKET/**/*.woff2
          
          # Make bucket publicly readable
          gsutil iam ch allUsers:objectViewer gs://$FRONTEND_BUCKET
          
          # Configure website
          gsutil web set -m index.html -e 404.html gs://$FRONTEND_BUCKET
          
          # Create redirect for root path
          echo '<html><head><meta http-equiv="refresh" content="0; url=/index.html"></head></html>' | gsutil -h "Content-Type:text/html" cp - gs://$FRONTEND_BUCKET/index.html 